# Generated by Django 3.0.5 on 2020-04-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank='False', max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
